version = 0.1

[default.build.parameters]
cached = true

[default.deploy.parameters]
stack_name        = "line-rich-menu-app-stack"
s3_prefix         = "line-rich-menu-app-stack-moritoki"
region            = "ap-northeast-1"
capabilities      = "CAPABILITY_IAM"
confirm_changeset = false
disable_rollback  = false
resolve_s3        = true